### ISSUE TITLE
What is the progress with Core version?

### ISSUE THREAD

**Issue by xperiandri** [juergenpf/Geodesy#2]
I see a project but no NuGet package released

**Comment by juergenpf** [comment]
No technical problem, just didn't have time in recent weeks. Will work on it soon.

**Comment by juergenpf** [comment]
I removed the Geodesy.Core project from the VS2015 build, will create a branch for VS2017 and place it there, simply because Core support is smoother there. From that I'll create a NuGet package containing Core support. Will do that sometime in February.
