### ISSUE TITLE
Implement IEquatable<T> on IComparable<T> structs

### ISSUE THREAD

**Issue by xperiandri** [juergenpf/Geodesy#3]
As GlobalCoordinates, Angle and some other structs can be checked for equality I think it will be reasonable to implement IEquatable<T> as it only 1 additional method with trivial logic.
IComparable equality is not the same as IEquatable equality.
IComparable equality means that the order of two instances can be determined.
While IEquatable equality means exact equality.

**Comment by juergenpf** [comment]
Thx, you're right. Will add it in one of the next drops.

**Comment by juergenpf** [comment]
I've implemented, will push soon (also to NuGet feed)
